apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}} -deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Never
          name: {{.Release.Name}}-client
          ports:
            - containerPort: 80
