apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
  type: ClusterIP
  ports:
    - name: {{.Release.Name}}-listener
      port: 80
      targetPort: 80
  selector:
    app: client
