apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - image: todos:0.1
          imagePullPolicy: Never
          name: todos
          ports:
            - containerPort: 8080
